[package]
name = "minimast"
version = "0.1.0"
authors = ["Antoine Choppin <antoine@japonophile.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
